name: Scrape latest data

# This workflow runs when someone pushes to the repository, manually on GitHub, and scheduled every day at 2:10 am
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '10 2 * * *'

jobs:
  scheduled:
    # Run workflow on a Ubuntu Linux virtual machine
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - name: Check out this repo
        uses: actions/checkout@v2
      # Setup a Python environment with the latest Python version
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      # Install requests and beautifulsoup4
      - name: Install dependencies
        run: |-
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 pandas
      # Run web scraper
      - name: Run scraper
        run: |-
          python ./scraper/users.py && ./scraper/trips.py
      # Add and commit changes (if any)
      - name: Commit and push if it changed
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push